### ISSUE TITLE
Request: create conditional step

### ISSUE THREAD

**Issue by jgiovaresco** [CircleCI-Public/circleci-config-sdk-ts#152]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I'd like to write a ReusableCommand having a conditional step based on the value of the parameter:

```
parameters:
  tag:
    type: string
    default: ""

steps:
  - when:
      condition: <<parameters.tag>>
      steps:
        - run: |
            export TAG=<< parameters.tag >>
            echo "export TAG=$TAG" >> $BASH_ENV
  - unless:
      condition: <<parameters.tag>>
      steps:
        - run:
            name: Compute Tag
            command: |
              export TAG=$(echo "${CIRCLE_BRANCH:0:15}-${CIRCLE_SHA1:0:7}" | sed -E 's/[~^]+//g' | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+|-+$//g' | tr A-Z a-z)
              echo "export TAG=$TAG" >> $BASH_ENV
```

### Describe the solution you'd like

Something like:

```
new reusable.ReusableCommand(
    'my-command',
    [
        new When("<<parameters.tag>>", [
            new commands.Run({
                command: `export TAG=<< parameters.tag >>
                echo "export TAG=$TAG" >> $BASH_ENV`,
            }),
        ]),
        new Unless("<<parameters.tag>>", [
            new commands.Run({
                command: `export TAG=$(echo "\${CIRCLE_BRANCH:0:15}-\${CIRCLE_SHA1:0:7}" | sed -E 's/[~^]+//g' | sed -E 's/[^a-zA-Z0-9]+/-/g' | sed -E 's/^-+|-+$//g' | tr A-Z a-z)
                echo "export TAG=$TAG" >> $BASH_ENV`,
            }),
        ]),
    ],
    new parameters.CustomParametersList([
        new parameters.CustomParameter(
            "tag",
            "string",
            "",
        )
    ]),
);
```

### Teachability, documentation, adoption, migration strategy

This would allow users to write ReusableCommand having a conditional step

### What is the motivation / use case for changing the behavior?

To have consistency on how to write command with Yaml and SDK
