### ISSUE TITLE
Request: Example of accessing Pipeline parameters in Config SDK

### ISSUE THREAD

**Issue by Kylmakalle** [CircleCI-Public/circleci-config-sdk-ts#171]
### Is there an existing issue that is already proposing this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe it

I'm unable to find a way to access pipeline parameters in JS/TS code.
I see there're some implementations related to [Git or VCS project itself](https://circleci-public.github.io/circleci-config-sdk-ts/classes/Pipeline.html#git), but I was unable to access any custom parameters during setup stage.
That being said, I also assume that any parameters that were passed to the pipeline trigger should be exposed in setup config, since CircleCI will raise a warning `⚠️ Unexpected argument(s): foo`

<img width="702" alt="image" src="https://user-images.githubusercontent.com/24507532/207284800-07eaaf9b-6933-4d06-a67b-00e4b7263731.png">

### Describe the solution you'd like

Such as `config.pipeline.git()`, we can have a `config.pipeline.parameters()`, which I expect to be a dictionary of parameters or even something more type-safe.

### Teachability, documentation, adoption, migration strategy

.

### What is the motivation / use case for changing the behavior?

- Adapting config to external triggers
- Providing more flexibility for dynamic configuring

**Comment by KyleTryon** [comment]
Hello @Kylmakalle. While I would like to support pipelines eventually (and they are currently defined), it is not possible today to get the pipeline values from within the job. CircleCI's pipeline parameters are a config-level construct that is "processed" out before the config is actually run. The code that is executed within a job unfortunately has no knowledge of a pipeline or pipeline parameter. We would like to get there at some point but it may require some changes outside this SDK. We may look to remove it from the SDK for the time-being to avoid confusion, thank you for pointing that out.

What use-case were you attempting? From my experimentation, what I would recommend is setting any similar type values to environment variables, which will be available at runtime.

example:

```yaml
version: 2.1
orbs:
  continuation: circleci/continuation@0.3.1
  node: circleci/node@5.0.2
setup: true
parameters:
  my-pipeline-parameter:
    type: string
    default: "foo/bar"
jobs:
  generate-config:
    executor: node/default
    environment:
        PARAM_PIPELINE_VALUE: <<pipeline.parameters.my-pipeline-parameter>>
    steps:
      - checkout
      - node/install-packages:
          app-dir: .circleci/dynamic
      - run:
          name: Generate config
          command: node .circleci/dynamic/index.js
```

This will populate `PARAM_PIPELINE_VALUE` with the value you are looking for. Then you can reference it as:

```node
process.env.my-pipeline-parameter
```
